'use client';
import { useEffect, useMemo, useState } from 'react';
import { LayoutDashboard, Users, Building2, Handshake, BriefcaseBusiness, CheckSquare, WalletCards, Mail, Plus, Search, Bell, ChevronDown, X, RefreshCw, KanbanSquare, List, Trash2, Pencil, Eye } from 'lucide-react';
import { supabase } from '../lib/supabase';

const modules=[['dashboard','Dashboard',LayoutDashboard],['leads','Leads',Users],['accounts','Accounts',Building2],['contacts','Contacts',Users],['deals','Deals',Handshake],['projects','Projects',BriefcaseBusiness],['activities','Activities',CheckSquare],['collections','Collections',WalletCards],['inbox','Sales Inbox',Mail]];
const config={
 leads:{table:'leads',title:'Leads',columns:[['lead_name','Lead'],['source','Source'],['status','Status'],['estimated_value','Value'],['sales_probability','Probability']]},
 accounts:{table:'companies',title:'Accounts',columns:[['name','Account'],['industry','Industry'],['phone','Phone'],['email','Email']]},
 contacts:{table:'contacts',title:'Contacts',columns:[['first_name','First Name'],['last_name','Last Name'],['job_title','Job Title'],['phone','Phone'],['email','Email']]},
 deals:{table:'deals',title:'Deals',columns:[['name','Deal'],['stage','Stage'],['estimated_value','Value'],['sales_probability','Probability'],['expected_close_date','Expected Close']]},
 projects:{table:'projects',title:'Projects',columns:[['project_name','Project'],['project_type','Type'],['status','Status'],['contract_value','Contract Value']]},
 activities:{table:'activities',title:'Activities',columns:[['subject','Subject'],['activity_type','Type'],['status','Status'],['priority','Priority'],['due_at','Due']]},
 collections:{table:'collections',title:'Collections',columns:[['invoice_reference','Invoice'],['amount_due','Due'],['amount_collected','Collected'],['collection_status','Status'],['due_date','Due Date']]},
 inbox:{table:'sales_inbox',title:'Sales Inbox',columns:[['sender_name','Sender'],['subject','Subject'],['ai_status','AI Status'],['ai_probability','Probability'],['received_at','Received']]}
};

export default function Home(){
 const[active,setActive]=useState('dashboard'),[showAdd,setShowAdd]=useState(false),[query,setQuery]=useState(''),[refresh,setRefresh]=useState(0),[selected,setSelected]=useState(null);
 const title=modules.find(x=>x[0]===active)?.[1]||'Dashboard';
 return <div className="app-shell"><aside className="sidebar"><div className="brand"><span className="brand-mark">E</span><div><strong>EMDAD</strong><small>CRM</small></div></div><button className="btn primary new-record" onClick={()=>setShowAdd(true)}><Plus size={16}/> New Record</button><div className="nav-label">WORKSPACE</div><nav className="nav">{modules.map(([id,label,Icon])=><button key={id} className={active===id?'active':''} onClick={()=>{setActive(id);setSelected(null)}}><Icon size={17}/><span>{label}</span></button>)}</nav><div className="sidebar-foot">EMDAD Sales Workspace<br/><span>CRM V2</span></div></aside><main className="main"><header className="topbar"><div className="global-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search records..."/></div><div className="top-actions"><button className="icon-btn"><Bell size={18}/></button><div className="workspace">Sales Workspace <ChevronDown size={14}/></div></div></header><section className="content"><div className="breadcrumb">Sales Workspace <span>/</span> {title}</div><div className="page-head"><div><h1>{title}</h1><p>{active==='dashboard'?'Your sales command center.':`Manage and track your ${title.toLowerCase()} in one place.`}</p></div>{active!=='dashboard'&&<button className="btn primary" onClick={()=>setShowAdd(true)}><Plus size={16}/> Add {title.slice(0,-1)}</button>}</div>{active==='dashboard'?<Dashboard refresh={refresh}/>:<ModulePage module={active} query={query} refresh={refresh} onRefresh={()=>setRefresh(x=>x+1)} onSelect={setSelected}/>}</section></main>{showAdd&&<CreateModal module={active} onClose={()=>setShowAdd(false)} onCreated={()=>{setShowAdd(false);setRefresh(x=>x+1)}}/>}{selected&&<RecordDrawer module={active} record={selected} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);setRefresh(x=>x+1)}}/>}</div>
}
function Dashboard({refresh}){const[data,setData]=useState({open_deals:0,pipeline_value:0,active_projects:0,outstanding:0}),[loading,setLoading]=useState(true);useEffect(()=>{let a=true;(async()=>{if(!supabase){setLoading(false);return}const{data,error}=await supabase.from('crm_dashboard').select('*').single();if(a&&!error&&data)setData(data);setLoading(false)})();return()=>{a=false}},[refresh]);const stats=[['Open Deals',data.open_deals,'opportunities'],['Pipeline Value',money(data.pipeline_value),'weighted pipeline'],['Active Projects',data.active_projects,'projects'],['Outstanding',money(data.outstanding),'to collect']];return <><div className="grid stats">{stats.map(([l,v,s])=><div className="metric-card" key={l}><div className="metric-top"><span>{l}</span><span className="dot"/></div><div className="metric-value">{loading?'—':v}</div><div className="metric-sub">{s}</div></div>)}</div><div className="dashboard-grid"><div className="panel"><div className="panel-head"><div><h3>Sales Pipeline</h3><span>Open opportunities by stage</span></div></div><Pipeline/></div><div className="panel"><div className="panel-head"><div><h3>Upcoming Activities</h3><span>Next actions and follow-ups</span></div></div><Activities/></div></div></>}
function Pipeline(){const[rows,setRows]=useState([]);useEffect(()=>{(async()=>{if(!supabase)return;const{data}=await supabase.from('pipeline_deals').select('*').order('estimated_value',{ascending:false}).limit(8);setRows(data||[])})()},[]);if(!rows.length)return <div className="empty">No opportunities in the pipeline yet.<br/><small>Deals with probability ≥ 50% appear here.</small></div>;return <div className="pipeline-list">{rows.map(r=><div className="pipeline-row" key={r.id}><div className="record-avatar">{(r.name||'D')[0]}</div><div className="grow"><strong>{r.name}</strong><span>{r.company_name||'No account'} · {r.stage}</span></div><b>{money(r.estimated_value)}</b></div>)}</div>}
function Activities(){const[rows,setRows]=useState([]);useEffect(()=>{(async()=>{if(!supabase)return;const{data}=await supabase.from('activities').select('*').eq('status','Open').order('due_at',{ascending:true}).limit(6);setRows(data||[])})()},[]);if(!rows.length)return <div className="empty">No activities scheduled.<br/><small>Create calls, meetings, and follow-ups here.</small></div>;return <div className="activity-list">{rows.map(r=><div className="activity-row" key={r.id}><div className="activity-icon"><CheckSquare size={15}/></div><div className="grow"><strong>{r.subject}</strong><span>{r.activity_type} · {formatDate(r.due_at)}</span></div><span className="status-pill">{r.priority}</span></div>)}</div>}
function ModulePage({module,query,refresh,onRefresh,onSelect}){const c=config[module],[view,setView]=useState(module==='deals'?'kanban':'list'),[rows,setRows]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');useEffect(()=>{let a=true;(async()=>{setLoading(true);setError('');if(!supabase){setLoading(false);return}const{data,error}=await supabase.from(c.table).select('*').order('created_at',{ascending:false}).limit(100);if(a){setRows(data||[]);if(error)setError(error.message);setLoading(false)}})();return()=>{a=false}},[c.table,refresh]);const filtered=useMemo(()=>rows.filter(r=>!query||Object.values(r).some(v=>String(v??'').toLowerCase().includes(query.toLowerCase()))),[rows,query]);async function remove(id){if(!supabase||!window.confirm('Delete this record?'))return;const{error}=await supabase.from(c.table).delete().eq('id',id);if(error)setError(error.message);else setRows(x=>x.filter(r=>r.id!==id))}return <div className="panel table-panel"><div className="table-toolbar"><div><strong>{filtered.length} records</strong><span>{supabase?'Connected to Supabase':'Add environment variables to connect'}</span></div><div className="toolbar-actions"><button className="icon-text" onClick={onRefresh}><RefreshCw size={15}/> Refresh</button>{module==='deals'&&<div className="view-toggle"><button className={view==='list'?'selected':''} onClick={()=>setView('list')}><List size={14}/></button><button className={view==='kanban'?'selected':''} onClick={()=>setView('kanban')}><KanbanSquare size={14}/></button></div>}</div></div>{error?<div className="error">{error}</div>:loading?<div className="empty">Loading {c.title.toLowerCase()}...</div>:view==='kanban'?<DealKanban rows={filtered} onSelect={onSelect}/>:<div className="table-wrap"><table className="table"><thead><tr>{c.columns.map(([,label])=><th key={label}>{label}</th>)}<th></th></tr></thead><tbody>{filtered.map(r=><tr key={r.id} onDoubleClick={()=>onSelect(r)}><td onClick={()=>onSelect(r)}>{formatCell(r[c.columns[0][0]],c.columns[0][0])}</td>{c.columns.slice(1).map(([key])=><td key={key}>{formatCell(r[key],key)}</td>)}<td><button className="row-action" onClick={()=>onSelect(r)} title="Open"><Eye size={14}/></button><button className="row-delete" onClick={()=>remove(r.id)} title="Delete"><Trash2 size={14}/></button></td></tr>)}{!filtered.length&&<tr><td colSpan={c.columns.length+1}><div className="empty">No {c.title.toLowerCase()} found.</div></td></tr>}</tbody></table></div>}</div>}
function DealKanban({rows,onSelect}){const stages=['New','Qualified','Proposition','Proposal sent','Follow-up','Negotiation','Won','Lost'];return <div className="kanban">{stages.map(stage=><div className="kanban-col" key={stage}><div className="kanban-head"><strong>{stage}</strong><span>{rows.filter(r=>(r.stage||'New')===stage).length}</span></div>{rows.filter(r=>(r.stage||'New')===stage).map(r=><div className="deal-card" key={r.id} onClick={()=>onSelect(r)}><strong>{r.name}</strong><span>{r.company_name||'No account'}</span><b>{money(r.estimated_value)}</b><small>{Number(r.sales_probability||0)}% probability</small></div>)}</div>)}</div>}
function RecordDrawer({module,record,onClose,onSaved}){const c=config[module];const[form,setForm]=useState(record||{}),[saving,setSaving]=useState(false),[error,setError]=useState('');useEffect(()=>setForm(record||{}),[record]);const editable=c.columns.filter(([key])=>!['created_at','updated_at','id'].includes(key));async function save(){if(!supabase)return;setSaving(true);setError('');const payload={};editable.forEach(([key])=>{if(form[key]!==undefined)payload[key]=form[key]});const{error}=await supabase.from(c.table).update(payload).eq('id',record.id);if(error)setError(error.message);else onSaved();setSaving(false)}return <div className="drawer-backdrop" onMouseDown={onClose}><aside className="record-drawer" onMouseDown={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">{c.title.slice(0,-1)}</span><h2>{record[c.columns[0][0]]||'Record'}</h2><small>Record ID: {record.id}</small></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><div className="drawer-body"><div className="detail-grid">{editable.map(([key,label])=><label key={key}>{label}<input value={form[key]??''} onChange={e=>setForm({...form,[key]:e.target.value})}/></label>)}</div><div className="drawer-section"><h3>System Information</h3><div className="system-info"><span>Created</span><b>{formatDate(record.created_at)}</b><span>Updated</span><b>{formatDate(record.updated_at)}</b></div></div></div><div className="drawer-actions"><button className="btn" onClick={onClose}>Cancel</button><button className="btn primary" disabled={saving} onClick={save}><Pencil size={15}/>{saving?'Saving...':'Save Changes'}</button></div>{error&&<div className="error drawer-error">{error}</div>}</aside></div>}
function CreateModal({module,onClose,onCreated}){const target=module==='dashboard'?'companies':config[module]?.table||'companies';const[name,setName]=useState(''),[value,setValue]=useState(''),[probability,setProbability]=useState('50'),[saving,setSaving]=useState(false),[error,setError]=useState('');const labels={companies:'Account Name',contacts:'First Name',leads:'Lead Name',deals:'Deal Name',projects:'Project Name',activities:'Subject',collections:'Invoice Reference',sales_inbox:'Subject'};async function save(){if(!supabase){setError('Supabase environment variables are not configured.');return}if(!name.trim()){setError('Name is required.');return}setSaving(true);setError('');const payload={},key=target==='companies'?'name':target==='contacts'?'first_name':target==='leads'?'lead_name':target==='deals'?'name':target==='projects'?'project_name':target==='activities'?'subject':target==='collections'?'invoice_reference':'subject';payload[key]=name.trim();if(['leads','deals','projects'].includes(module)&&value)payload[module==='projects'?'contract_value':'estimated_value']=Number(value)||0;if(['leads','deals'].includes(module))payload.sales_probability=Math.max(0,Math.min(100,Number(probability)||0));const{error}=await supabase.from(target).insert(payload);if(error)setError(error.message);else onCreated();setSaving(false)}return <div className="modal-backdrop" onMouseDown={onClose}><div className="modal" onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><h2>New {config[module]?.title?.slice(0,-1)||'Account'}</h2><p>Create a record in your CRM.</p></div><button className="icon-btn" onClick={onClose}><X size={18}/></button></div><label>{labels[target]||'Name'}<input autoFocus value={name} onChange={e=>setName(e.target.value)} placeholder="Enter name..."/></label>{['leads','deals','projects'].includes(module)&&<label>Estimated Value<input type="number" value={value} onChange={e=>setValue(e.target.value)} placeholder="0"/></label>}{['leads','deals'].includes(module)&&<label>Sales Probability %<input type="number" min="0" max="100" value={probability} onChange={e=>setProbability(e.target.value)}/></label>}{error&&<div className="error">{error}</div>}<div className="modal-actions"><button className="btn" onClick={onClose}>Cancel</button><button className="btn primary" disabled={saving} onClick={save}>{saving?'Saving...':'Create Record'}</button></div></div></div>}
function money(v){return `EGP ${Number(v||0).toLocaleString('en-US',{maximumFractionDigits:0})}`}function formatDate(v){if(!v)return'No date';const d=new Date(v);return Number.isNaN(d.getTime())?'—':d.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}function formatCell(v,key){if(v===null||v===undefined||v==='')return'—';if(key.includes('value')||key.includes('amount'))return money(v);if(key.includes('probability'))return`${v}%`;if(key.includes('date')||key.endsWith('_at'))return formatDate(v);return String(v)}
