export const dynamic = 'force-dynamic';

export async function GET() {
  const source = 'https://raw.githubusercontent.com/Walid-Mahmoudi/EMDAD-CRM-V2/main/crm-v3.html';
  const response = await fetch(source, { cache: 'no-store' });
  if (!response.ok) return new Response('EMDAD CRM V3 is temporarily unavailable.', { status: 502 });
  let html = await response.text();

  // Reliable profile bootstrap: never silently downgrade an authenticated user to Sales.
  const oldBoot = "let r=await db.from('profiles').select('*').eq('id',u.id).maybeSingle();me=r.data||{id:u.id,full_name:u.email,role:'sales'};";
  const newBoot = "let r=await db.rpc('get_my_profile');if(r.error||!r.data){let rr=await db.rpc('get_my_role');if(rr.error||!rr.data){console.error('Profile load failed',r.error,rr.error);return msg('تعذر تحميل صلاحيات الحساب. تواصل مع المدير.',true)}me={id:u.id,full_name:u.email,role:rr.data}}else me=r.data;";
  html = html.replace(oldBoot, newBoot);

  // Admin user management.
  const oldNav = "let items=[['dashboard','Dashboard'],['projects','Projects'],['companies','Customers'],['followups','Follow-ups'],['meetings','Meetings']];";
  const newNav = "let items=[['dashboard','Dashboard'],['projects','Projects'],['companies','Customers'],['followups','Follow-ups'],['meetings','Meetings']];if(isAdmin())items.push(['users','Users']);";
  html = html.replace(oldNav, newNav);

  const marker = "function go(p){state.page=p;nav();({dashboard:dashboard,projects:projects,companies:companiesPage,followups:followupsPage,meetings:meetingsPage}[p]||dashboard)()}";
  const replacement = `async function usersPage(){if(!isAdmin())return dashboard();let r=await db.rpc('admin_list_profiles');if(r.error)return pageError(r.error);let rows=r.data||[];$('page').innerHTML=\`<div class="toolbar"><h2>User Management</h2><span class="right"></span></div><div class="card"><div class="hint">Admin only — manage role, active status and user details.</div><div class="tablewrap"><table><tr><th>Name</th><th>Phone</th><th>Role</th><th>Status</th><th>Created</th><th></th></tr>\${rows.map(x=>\`<tr><td><input id="un-\${x.id}" value="\${esc(x.full_name||'')}"></td><td><input id="up-\${x.id}" value="\${esc(x.phone||'')}"></td><td><select id="ur-\${x.id}">\${['admin','sales','technical_support','management'].map(z=>\`<option value="\${z}" \${x.role===z?'selected':''}>\${z}</option>\`).join('')}</select></td><td><select id="ua-\${x.id}"><option value="true" \${x.is_active?'selected':''}>Active</option><option value="false" \${!x.is_active?'selected':''}>Inactive</option></select></td><td>\${dt(x.created_at)}</td><td><button onclick="saveUserProfile('\${x.id}')">Save</button></td></tr>\`).join('')}</table></div></div>\`}
async function saveUserProfile(id){if(!isAdmin())return;let r=await db.rpc('admin_update_profile',{p_id:id,p_role:$('ur-'+id).value,p_is_active:$('ua-'+id).value==='true',p_full_name:$('un-'+id).value,p_phone:$('up-'+id).value});if(r.error)return alert(r.error.message);usersPage()}
${marker.replace("meetings:meetingsPage", "meetings:meetingsPage,users:usersPage")}`;
  html = html.replace(marker, replacement);

  // EMDAD visual system: restrained engineering/corporate UI. No icon-font pseudo elements.
  const stylePatch = `<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
:root{--red:#c83535;--red2:#a92d2d;--charcoal:#242a30;--ink:#30363d;--muted:#737a82;--bg:#f4f5f6;--line:#e2e5e8;--white:#fff;--shadow:0 10px 30px rgba(30,36,42,.08)}
*{box-sizing:border-box}html,body{min-height:100%;font-family:Inter,Arial,Tahoma,sans-serif}body{margin:0;background:linear-gradient(180deg,#fafbfc 0%,#f1f3f5 100%);color:var(--ink);letter-spacing:-.12px}body:before{content:'';position:fixed;inset:0;pointer-events:none;background:linear-gradient(135deg,transparent 0 48%,rgba(200,53,53,.025) 48% 49%,transparent 49%),linear-gradient(315deg,transparent 0 72%,rgba(36,42,48,.02) 72% 73%,transparent 73%);z-index:0}
button{appearance:none;border:0;border-radius:9px;padding:10px 16px;background:var(--red);color:#fff;box-shadow:0 5px 14px rgba(200,53,53,.16);font:600 14px Inter,Arial,sans-serif;cursor:pointer;transition:background .15s,transform .15s,box-shadow .15s}button:hover{background:var(--red2);transform:translateY(-1px)}button:active{transform:translateY(0)}button.secondary{background:#fff;color:var(--charcoal);border:1px solid #dfe2e5;box-shadow:none}button.danger{background:#7f1d1d}
.top{position:sticky;top:0;z-index:10;background:var(--charcoal);color:#fff;padding:16px 24px;border-bottom:3px solid var(--red);box-shadow:0 4px 20px rgba(0,0,0,.14)}.top:after{content:'';position:absolute;right:24px;top:0;width:70px;height:3px;background:var(--red)}.brand{font-size:19px;font-weight:800;letter-spacing:.2px}.brand:before{content:'EMDAD';color:#fff;letter-spacing:3px;margin-right:11px}.brand:after{content:'  Engineering Solutions';font-size:12px;color:#c8cdd2;font-weight:500;letter-spacing:.5px}
.wrap{position:relative;z-index:1;max-width:1480px;margin:auto;padding:22px}.nav{display:flex;gap:3px;flex-wrap:wrap;padding:5px;margin-bottom:18px;background:rgba(255,255,255,.92);border:1px solid var(--line);border-radius:12px;box-shadow:var(--shadow)}.nav button{position:relative;background:transparent;color:#626970;border:0;box-shadow:none;border-radius:8px;padding:10px 14px;font-size:13px}.nav button:hover{background:#f5f6f7;color:var(--charcoal);transform:none}.nav button.on{background:var(--charcoal);color:#fff}
.card{background:rgba(255,255,255,.98);border:1px solid var(--line);border-radius:14px;padding:18px;box-shadow:var(--shadow)}.kpi{position:relative;overflow:hidden}.kpi:before{content:'';position:absolute;right:0;top:0;bottom:0;width:4px;background:var(--red)}.kpi h2{font-size:24px;margin:8px 0 0;font-weight:800}.kpi small{color:var(--muted);font-weight:600}.toolbar{gap:8px}.toolbar h2,.sectionTitle h3{font-weight:800;color:var(--charcoal)}
input,select,textarea{width:100%;padding:11px 12px;border:1px solid #d5d9dd;border-radius:9px;background:#fff;color:var(--ink);font:400 14px Inter,Arial,Tahoma,sans-serif;outline:none;transition:border-color .15s,box-shadow .15s}input:focus,select:focus,textarea:focus{border-color:var(--red);box-shadow:0 0 0 3px rgba(200,53,53,.09)}label{color:#3f464d;font-weight:600;font-size:13px;margin:11px 0 6px}.hint{color:var(--muted)}th{background:#f3f4f5;color:#3c434a;font-weight:700}tr.click:hover{background:#fff7f7}.badge{font-weight:700;border-radius:999px}.modalbox{border:1px solid var(--line);box-shadow:0 24px 65px rgba(0,0,0,.25)}
/* Login: premium, quiet, and fully touch-safe on mobile. */
.auth{position:relative;isolation:isolate;min-height:100vh;background:linear-gradient(145deg,#20262c 0%,#2c333a 55%,#191e23 100%);padding:24px;overflow:hidden}.auth:before{content:'';position:absolute;inset:-15%;pointer-events:none;z-index:-1;background:linear-gradient(135deg,transparent 47%,rgba(200,53,53,.12) 47.3%,rgba(200,53,53,.03) 49%,transparent 49.4%),linear-gradient(315deg,transparent 68%,rgba(255,255,255,.035) 68.2%,transparent 68.6%)}.authbox{position:relative;z-index:2;width:min(430px,100%);padding:38px 34px 30px;border:1px solid rgba(255,255,255,.35);border-top:4px solid var(--red);border-radius:18px;background:rgba(255,255,255,.985);box-shadow:0 28px 80px rgba(0,0,0,.38)}.authbox:before{content:'E';display:grid;place-items:center;width:46px;height:46px;border-radius:50%;margin:0 auto 18px;background:var(--red);color:#fff;font-size:24px;font-weight:800;box-shadow:0 8px 20px rgba(200,53,53,.25)}.authbox h1{margin:0;text-align:center;font-size:30px;line-height:1.1;color:var(--charcoal);font-weight:800;letter-spacing:-1.2px}.authbox h1:before{content:'EMDAD';display:block;margin-bottom:8px;color:var(--red);font-size:12px;letter-spacing:4px}.authbox h1:after{content:'Engineering Solutions';display:block;margin-top:8px;color:#7b8187;font-size:11px;font-weight:500;letter-spacing:1.4px}.authbox>p.muted{text-align:center;margin:13px 0 27px;color:#6c737a;font-size:13px}.authbox label{text-align:left;direction:ltr;margin-top:14px}.authbox input{height:48px;font-size:15px;direction:ltr;text-align:left;position:relative;z-index:3}.authbox .toolbar{display:flex;flex-direction:column;gap:10px;margin-top:20px}.authbox .toolbar button{width:100%;height:48px;font-size:14px;margin:0}.authbox .toolbar button:before{content:none!important}.authbox .hint{text-align:center;margin-top:15px;line-height:1.6}
/* Explicitly keep the decorative layers from stealing pointer/touch events. */
.auth:before,body:before{pointer-events:none!important}.authbox,.authbox input,.authbox button{pointer-events:auto!important}
@media(max-width:700px){.wrap{padding:10px}.top{padding:13px 15px}.brand{font-size:16px}.brand:after{display:none}.nav{overflow-x:auto;flex-wrap:nowrap;border-radius:10px;margin-bottom:12px}.nav button{white-space:nowrap;padding:9px 12px}.card{padding:14px}.toolbar>*{max-width:100%;width:100%}.grid{gap:8px}.kpi h2{font-size:20px}.auth{padding:14px}.authbox{width:min(430px,100%);padding:30px 22px 24px;border-radius:16px}.authbox h1{font-size:27px}}
</style>`;
  html = html.replace('</head>', stylePatch + '</head>');

  return new Response(html,{status:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, max-age=0'}});
}
