export const dynamic = 'force-dynamic';

export async function GET() {
  const source = 'https://raw.githubusercontent.com/Walid-Mahmoudi/EMDAD-CRM-V2/main/crm-v3.html';
  const response = await fetch(source, { cache: 'no-store' });
  if (!response.ok) return new Response('EMDAD CRM V3 is temporarily unavailable.', { status: 502 });
  let html = await response.text();

  const oldBoot = "let r=await db.from('profiles').select('*').eq('id',u.id).maybeSingle();me=r.data||{id:u.id,full_name:u.email,role:'sales'};";
  const newBoot = "let r=await db.rpc('get_my_profile');if(r.error||!r.data){let rr=await db.rpc('get_my_role');if(rr.error||!rr.data){console.error('Profile load failed',r.error,rr.error);return msg('تعذر تحميل صلاحيات الحساب. تواصل مع المدير.',true)}me={id:u.id,full_name:u.email,role:rr.data}}else me=r.data;";
  html = html.replace(oldBoot, newBoot);

  const stylePatch = `<style>
@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap');
@import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css');
:root{--emdad-red:#c83535;--emdad-red-dark:#a92727;--emdad-charcoal:#252a30;--emdad-gray:#5b6066;--emdad-light:#f4f5f6;--emdad-line:#e1e4e7;--emdad-white:#fff;--emdad-shadow:0 12px 32px rgba(37,42,48,.09)}
*{box-sizing:border-box}html{background:var(--emdad-light)}body{margin:0;font-family:Inter,Arial,Tahoma,sans-serif;background:linear-gradient(180deg,#f8f9fa 0,#f0f2f4 100%);color:var(--emdad-charcoal);letter-spacing:-.1px}
body:before{content:'';position:fixed;inset:0;pointer-events:none;background-image:linear-gradient(135deg,rgba(200,53,53,.018) 25%,transparent 25%),linear-gradient(315deg,rgba(37,42,48,.015) 25%,transparent 25%);background-size:44px 44px;opacity:.55}
button{border:0;border-radius:10px;padding:10px 15px;background:linear-gradient(135deg,var(--emdad-red),var(--emdad-red-dark));color:#fff;box-shadow:0 6px 16px rgba(200,53,53,.2);transition:.18s;font-family:inherit;font-weight:600;cursor:pointer}button:hover{transform:translateY(-1px);filter:brightness(1.03)}button.secondary{background:#fff;color:var(--emdad-charcoal);border:1px solid var(--emdad-line);box-shadow:none}button.danger{background:#7f1d1d}
.top{position:relative;background:linear-gradient(135deg,#1d2228 0,#30363d 100%);padding:15px 24px;box-shadow:0 5px 24px rgba(0,0,0,.15);border-bottom:3px solid var(--emdad-red)}.top:after{content:'';position:absolute;right:24px;top:0;width:90px;height:3px;background:var(--emdad-red)}.brand{font-weight:800;letter-spacing:.3px}.brand:before{content:'EMDAD';display:inline-block;color:#fff;margin-right:12px;font-weight:800;letter-spacing:2px}.brand:after{content:' Engineering Solutions';color:#cfd3d7;font-weight:500;font-size:.82em}
.wrap{max-width:1500px;padding:22px;margin:auto}.nav{gap:6px;padding:7px;background:rgba(255,255,255,.96);border:1px solid var(--emdad-line);border-radius:15px;box-shadow:var(--emdad-shadow);display:flex;flex-wrap:wrap}.nav button{border:0;background:transparent;color:#535960;box-shadow:none;border-radius:10px;padding:10px 13px;font-weight:600}.nav button:hover{background:#f5f6f7;color:var(--emdad-charcoal);transform:none}.nav button.on{background:var(--emdad-charcoal);color:#fff;box-shadow:0 5px 14px rgba(37,42,48,.18)}
.card{background:rgba(255,255,255,.97);border:1px solid var(--emdad-line);border-radius:16px;padding:18px;box-shadow:var(--emdad-shadow)}.kpi{position:relative;overflow:hidden}.kpi:before{content:'';position:absolute;right:0;top:0;width:5px;height:100%;background:linear-gradient(180deg,var(--emdad-red),#8f2020)}.kpi:after{content:'↗';position:absolute;right:17px;bottom:13px;color:#d9dcdf;font-size:22px}.kpi h2{font-size:24px;letter-spacing:-.5px}.toolbar h2,.sectionTitle h3{font-weight:800;letter-spacing:-.5px}.hint{color:var(--emdad-gray)}
input,select,textarea{border:1px solid #d6dade;border-radius:10px;outline:none;transition:.15s;font-family:inherit;background:#fff}input:focus,select:focus,textarea:focus{border-color:var(--emdad-red);box-shadow:0 0 0 3px rgba(200,53,53,.10)}label{color:#3e444a;font-weight:600}th{background:#f0f1f3;color:#343a40;font-weight:700;border-bottom:2px solid #dfe2e5}tr.click:hover{background:#fff5f5}.badge{font-weight:700;border-radius:999px;padding:5px 9px}.modalbox{border:1px solid var(--emdad-line);box-shadow:0 25px 70px rgba(0,0,0,.28)}
.auth{position:relative;background:radial-gradient(circle at 50% 10%,#414950 0,#252a30 48%,#161a1e 100%);isolation:isolate}.auth:before{content:'';position:absolute;inset:0;pointer-events:none;z-index:0;background:linear-gradient(135deg,transparent 0 48%,rgba(200,53,53,.08) 48% 50%,transparent 50%)}.authbox{position:relative;z-index:1;border:0;border-top:4px solid var(--emdad-red);box-shadow:0 25px 70px rgba(0,0,0,.38);padding:30px}.authbox h1{font-weight:800;letter-spacing:-1px}.authbox h1:before{content:'EMDAD';display:block;font-size:14px;letter-spacing:3px;color:var(--emdad-red);margin-bottom:8px}.authbox h1:after{content:'Engineering Solutions';display:block;font-size:11px;letter-spacing:1.2px;color:#7a8086;margin-top:3px}
/* Professional icon language inspired by the company profile: target, HVAC, facility, technical and management symbols. */
button:before{font-family:'Font Awesome 6 Free';font-weight:900;margin-right:7px}.nav button:nth-child(1):before{content:'\\f3fd'}.nav button:nth-child(2):before{content:'\\f542'}.nav button:nth-child(3):before{content:'\\f0c0'}.nav button:nth-child(4):before{content:'\\f0e0'}.nav button:nth-child(5):before{content:'\\f073'}.nav button:nth-child(6):before{content:'\\f508'}.toolbar button:before{content:'\\2b'}.sectionTitle h3:before{content:'\\f0da';font-family:'Font Awesome 6 Free';font-weight:900;color:var(--emdad-red);margin-right:8px}.kpi:first-child h3:before{content:'\\f201'}.kpi:nth-child(2) h3:before{content:'\\f0ae'}.kpi:nth-child(3) h3:before{content:'\\f02d'}.kpi:nth-child(4) h3:before{content:'\\f571'}.kpi:nth-child(5) h3:before{content:'\\f155'}
@media(max-width:700px){.wrap{padding:10px}.top{padding:12px 14px}.brand{font-size:16px}.brand:after{display:none}.nav{border-radius:12px;padding:5px;overflow-x:auto;flex-wrap:nowrap}.nav button{white-space:nowrap;padding:8px 10px;font-size:12px}.card{padding:13px}.toolbar{gap:8px}.toolbar>*{max-width:100%;width:100%}.toolbar .right{display:none}.grid{gap:8px}.kpi h2{font-size:20px}.authbox{padding:22px;margin:10px}}
</style>`;
  html = html.replace('</head>', stylePatch + '</head>');

  const oldNav = "let items=[['dashboard','Dashboard'],['projects','Projects'],['companies','Customers'],['followups','Follow-ups'],['meetings','Meetings']];";
  const newNav = "let items=[['dashboard','Dashboard'],['projects','Projects'],['companies','Customers'],['followups','Follow-ups'],['meetings','Meetings']];if(isAdmin())items.push(['users','Users']);";
  html = html.replace(oldNav, newNav);

  const marker = "function go(p){state.page=p;nav();({dashboard:dashboard,projects:projects,companies:companiesPage,followups:followupsPage,meetings:meetingsPage}[p]||dashboard)()}";
  const replacement = `async function usersPage(){if(!isAdmin())return dashboard();let r=await db.rpc('admin_list_profiles');if(r.error)return pageError(r.error);let rows=r.data||[];$('page').innerHTML=\`<div class="toolbar"><h2>User Management</h2><span class="right"></span></div><div class="card"><div class="hint">Admin only — manage role, active status and user details.</div><div class="tablewrap"><table><tr><th>Name</th><th>Phone</th><th>Role</th><th>Status</th><th>Created</th><th></th></tr>\${rows.map(x=>\`<tr><td><input id="un-\${x.id}" value="\${esc(x.full_name||'')}"></td><td><input id="up-\${x.id}" value="\${esc(x.phone||'')}"></td><td><select id="ur-\${x.id}">\${['admin','sales','technical_support','management'].map(z=>\`<option value="\${z}" \${x.role===z?'selected':''}>\${z}</option>\`).join('')}</select></td><td><select id="ua-\${x.id}"><option value="true" \${x.is_active?'selected':''}>Active</option><option value="false" \${!x.is_active?'selected':''}>Inactive</option></select></td><td>\${dt(x.created_at)}</td><td><button onclick="saveUserProfile('\${x.id}')">Save</button></td></tr>\`).join('')}</table></div></div>\`}
async function saveUserProfile(id){if(!isAdmin())return;let r=await db.rpc('admin_update_profile',{p_id:id,p_role:$('ur-'+id).value,p_is_active:$('ua-'+id).value==='true',p_full_name:$('un-'+id).value,p_phone:$('up-'+id).value});if(r.error)return alert(r.error.message);usersPage()}
${marker.replace("meetings:meetingsPage", "meetings:meetingsPage,users:usersPage")}`;
  html = html.replace(marker, replacement);

  return new Response(html,{status:200,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store, max-age=0'}});
}
